# Generated by Django 4.2.6 on 2023-12-10 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("malfunctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelmalfunctions",
            name="date_time_closed",
        ),
        migrations.AddField(
            model_name="modelmalfunctions",
            name="date_closed",
            field=models.DateField(
                default=datetime.date(2023, 12, 10),
                verbose_name="Дата закрытия заявки",
            ),
        ),
        migrations.AddField(
            model_name="modelmalfunctions",
            name="executor_mechanics",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executor_mechanics",
                to="main.mechanicslist",
            ),
        ),
        migrations.AddField(
            model_name="modelmalfunctions",
            name="time_closed",
            field=models.TimeField(
                default=datetime.time(22, 22, 51, 275467),
                verbose_name="Время закрытия заявки",
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="date_time_accepted",
            field=models.DateField(verbose_name="Дата приема заявки"),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="mechanics",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mechanics",
                to="main.mechanicslist",
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="transfer_of_the_application",
            field=models.BooleanField(
                default=False, verbose_name="Передача по смене"
            ),
        ),
    ]
