variables:
  CI_IMAGE_BASE: $CI_IMAGE_BASE
  CI_REGISTRY_USER: $CI_REGISTRY_USER
  CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CI_REGISTRY: $CI_REGISTRY
  WEB_IMAGE_TAG: $CI_IMAGE_BASE/web:$CI_COMMIT_REF_SLUG

stages:
  - build
  - test
  - deploy

include:
  - .ci/web.yaml

deploy_job:
  stage: deploy
  only:
    - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cat ${PROD_ENV} >> ui/web/.env.production
    - cat ${PROD_ENV} >> .env.production
    - docker compose --file ui/web/docker-compose.prod.yaml --env-file .env.production down
    - docker compose --file ui/web/docker-compose.prod.yaml pull
    - docker compose --file ui/web/docker-compose.prod.yaml --env-file .env.production up -d
