version: "3.9"

services:
  app:
    image: registry.gitlab.com/web_briz_vlg:main
    container_name: django
    ports:
      - "8008:8000"
    env_file:
      - .env.production
    entrypoint: /code/entrypoint.sh
    depends_on:
      - cache
    tty: true
    stdin_open: true
  cache:
      image: redis:7.2.1-alpine
      container_name: redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      env_file:
        - .env.production
      ports:
        - '6379:6379'
      volumes:
        - cache:/data

  volumes:
    cache:
      driver: local
    postgresql-data:
