version: "3.3"

services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    volumes:
        - postgresql-data:/var/lib/postgresql/data
    ports:
        - "5435:5432"
  app:
    build: .
    container_name: django
    ports:
      - "80:8000"
    env_file:
      - .env
    command: sh -c "cd ./ui/web/ &&
      python manage.py migrate && 
      celery -A web.celery:app worker -B -l info --detach && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/local/app/
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
    cache:
      driver: local
    postgresql-data:
