version: "3.9"

services:
  db:
    image: postgres
    container_name: ivea-postgres
    env_file:
      - .env.development
    volumes:
        - postgresql-data:/var/lib/postgresql/data
    ports:
        - "5435:5432"
  app:
    build: .
    container_name: ivea-django
    ports:
      - "8008:8000"
    env_file:
      - .env.development
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    depends_on:
      - db
      - cache
    tty: true
    stdin_open: true
  cache:
    image: redis:7.2.1-alpine
    container_name: ivea-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env.development
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: ivea-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    env_file:
      - .env.development

volumes:
    cache:
      driver: local
    postgresql-data:
