apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: sealed-secrets-cert
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
data:
  {{- $files := .Files }}
  {{- range tuple "tls.crt" "tls.key" }}
  {{ . }}: {{ $files.Get . }}
  {{- end }}
