# Generated by Django 4.2.6 on 2023-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Адрес"),
                ),
                (
                    "num_house",
                    models.CharField(max_length=10, verbose_name="Номер дома"),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "Список адресов",
            },
        ),
        migrations.CreateModel(
            name="DispatcherList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fio",
                    models.CharField(
                        max_length=200, verbose_name="ФИО диспетчера"
                    ),
                ),
            ],
            options={
                "verbose_name": "диспетчер",
                "verbose_name_plural": "Список диспетчеров",
            },
        ),
        migrations.CreateModel(
            name="MechanicsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fio",
                    models.CharField(
                        max_length=200, verbose_name="ФИО механика"
                    ),
                ),
            ],
            options={
                "verbose_name": "механик",
                "verbose_name_plural": "Список механиков",
            },
        ),
    ]
