# Generated by Django 4.2.6 on 2023-12-10 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatcherlist",
            options={
                "verbose_name": "диспетчера",
                "verbose_name_plural": "Список диспетчеров",
            },
        ),
        migrations.AlterModelOptions(
            name="mechanicslist",
            options={
                "verbose_name": "механика",
                "verbose_name_plural": "Список механиков",
            },
        ),
    ]
