# Generated by Django 4.2.6 on 2023-12-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_dispatcherlist_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addresslist",
            name="num_house",
        ),
        migrations.AlterField(
            model_name="addresslist",
            name="address",
            field=models.CharField(verbose_name="Адрес"),
        ),
    ]
