# Generated by Django 4.2.6 on 2023-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_addresslist_num_house_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_router",
                    models.CharField(verbose_name="Название роутера"),
                ),
                ("emai", models.CharField(verbose_name="номер роутера")),
            ],
            options={
                "verbose_name": "роутер",
                "verbose_name_plural": "Список роутеров",
            },
        ),
        migrations.CreateModel(
            name="SimCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "ip",
                    models.CharField(max_length=12, verbose_name="ip симки"),
                ),
                (
                    "operator_name",
                    models.CharField(verbose_name="Наименование оператора"),
                ),
            ],
            options={
                "verbose_name": "симку",
                "verbose_name_plural": "Список симкарт",
            },
        ),
    ]
