apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector:
    app.name: ivea-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: ivea-django
  template:
    metadata:
      labels:
        app.name: ivea-django
      annotations:
        lastDeployedDate: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
      - name: gitlab-registry-credentials
      containers:
      - name: main
        imagePullPolicy: Always
        image: {{ .Values.images.admin }}
        command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
        envFrom:
          - secretRef:
              name: admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: admin-migrations-job-{{ .Release.Revision }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: main
          image: {{ .Values.images.admin }}
          imagePullPolicy: Always
          command: ["python3", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: admin
