# Generated by Django 4.2.6 on 2024-03-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("malfunctions", "0017_modelmalfunctions_date_time_transfer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="date_time_accepted",
            field=models.DateTimeField(
                null=True, verbose_name="Дата приема заявки"
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="num_house",
            field=models.CharField(verbose_name="Номер дома"),
        ),
    ]
