# Generated by Django 4.2.6 on 2024-03-12 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "malfunctions",
            "0018_alter_modelmalfunctions_date_time_accepted_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelmalfunctions",
            name="transfer_of_the_application",
        ),
    ]
