# Generated by Django 4.2.6 on 2024-03-19 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_routers_imei_alter_addresslist_address_and_more"),
        (
            "malfunctions",
            "0019_remove_modelmalfunctions_transfer_of_the_application",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="date_time_closed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата закрытия заявки"
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="date_time_transfer",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата передачи заявки механикам",
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="description",
            field=models.CharField(
                blank=True, null=True, verbose_name="Примечания"
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="dispatcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.dispatcherlist",
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="executor_mechanics",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="executor_mechanics",
                to="main.mechanicslist",
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="flat_or_tel",
            field=models.CharField(
                blank=True, verbose_name="Номер квартины или телефона"
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="malfunction_and_cause",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Неисправность и причина заявки",
            ),
        ),
        migrations.AlterField(
            model_name="modelmalfunctions",
            name="simple",
            field=models.CharField(
                blank=True, default="", null=True, verbose_name="Простой"
            ),
        ),
    ]
