# Generated by Django 4.2.6 on 2024-01-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_routers_emai_alter_simcard_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="routers",
            name="info_install",
            field=models.CharField(default="", verbose_name="Доп. информация"),
        ),
        migrations.AlterField(
            model_name="simcard",
            name="ip",
            field=models.CharField(max_length=15, verbose_name="IP симкарты"),
        ),
        migrations.AlterField(
            model_name="simcard",
            name="phone_number",
            field=models.CharField(
                max_length=12, verbose_name="Номер телефона"
            ),
        ),
    ]
