# Generated by Django 4.2.6 on 2024-03-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_routers_info_install_alter_simcard_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routers",
            name="imei",
            field=models.CharField(null=True, verbose_name="IMEI роутера"),
        ),
        migrations.AlterField(
            model_name="addresslist",
            name="address",
            field=models.CharField(unique=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="dispatcherlist",
            name="fio",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="ФИО диспетчера"
            ),
        ),
        migrations.AlterField(
            model_name="mechanicslist",
            name="fio",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="ФИО механика"
            ),
        ),
        migrations.AlterField(
            model_name="routers",
            name="info_install",
            field=models.CharField(
                blank=True, default="", verbose_name="Доп. информация"
            ),
        ),
        migrations.AlterField(
            model_name="routers",
            name="name_router",
            field=models.CharField(
                blank=True, verbose_name="Название роутера"
            ),
        ),
        migrations.AlterField(
            model_name="simcard",
            name="ip",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="IP симкарты"
            ),
        ),
        migrations.AlterField(
            model_name="simcard",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
