# Generated by Django 4.2.6 on 2024-03-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_routers_imei_alter_addresslist_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routers",
            name="emai",
        ),
        migrations.AlterField(
            model_name="routers",
            name="imei",
            field=models.CharField(unique=True, verbose_name="IMEI роутера"),
        ),
    ]
