# Generated by Django 4.2.6 on 2024-03-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_routers_emai_alter_routers_imei"),
    ]

    operations = [
        migrations.AddField(
            model_name="routers",
            name="sim_card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.simcard",
                verbose_name="Симкарта",
            ),
        ),
    ]
