version: "3.3"

services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    volumes:
        - postgresql-data:/var/lib/postgresql/data
    ports:
        - "5430:5432"
  app:
    build: .
    container_name: django
    ports:
      - "8008:8000"
    env_file:
      - .env
    entrypoint: /usr/local/app/entrypoint.sh
    volumes:
      - .:/usr/local/app
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
    cache:
      driver: local
    postgresql-data:
