version: "3.9"

services:
  app:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
    cache:
      driver: local
    postgresql-data:
